name: Meu Build e Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar make e ferramentas de build
        run: sudo apt-get update && sudo apt-get install -y make build-essential

      - name: Limpar projeto
        run: make clean

      # Seus outros passos aqui embaixo...
      - name: Compilar
        run: make build

      - name: Testar
        run: make test
